### ISSUE TITLE
queue: 队列接口设计

### ISSUE THREAD

**Issue by flycash** [gotomicro/ekit#103]
**仅限中文**

### 使用场景

有些时候我们会需要使用队列来完成一些操作。实际上大多数的场景，我们使用 channel 就足够了。但是在一些必要的场景下，我们还是需要队列。

在我个人的开发经历中，我会在一些特定的时候需要一些队列：
- 我需要遍历队列的时候
- 我需要删除队列里面的元素的时候
- 我需要优先级队列的时候
- 我需要基于时间的优先级队列的时候。尤其是这个队列，我在设计各种中间件的时候，有时候会需要按照时间来调度一些东西，比如说控制过期时间，那么这个时候我会非常希望有一个时间优先级队列，当我从队列头取元素的时候，我能够被阻塞，直到最近一个过期时间到了

### 行业分析
> 如果你知道有框架提供了类似功能，可以在这里描述，并且给出文档或者例子

这个东西主要参考 Java 里面的队列接口设计。我个人不太熟悉其它语言的队列接口，我们可以综合讨论。

### 可行方案
> 如果你有设计思路或者解决方案，请在这里提供。你可以提供多个方案，并且给出自己的选择

### 其它

该 issue 是一个设计类的 issue，所以你可以直接创建出来一个合并请求，我们在合并请求里面深入讨论队列接口设计

### 你设置的的 Go 环境?
> 上传 `go env` 的结果

**Comment by flyhigher139** [comment]
## 队列

```go
type Queue[T any] interface {
	Offer(e T) (bool, error)
	Poll() T
	Peek() T
}
```

## 阻塞队列

```go
type BlockingQueue[T any] interface {
	Queue[T]
	Put(ctx context.Context, e T) (bool, error)
	Take(ctx context.Context) (T, error)
}
```
阻塞队列，在队列的基础上，增加了阻塞入队出队的接口，通过context做超时控制或中断

## 迭代器

```go
type Iterator[T any] interface {
	HasNext() bool
	Next() (T, error)
}
```

为了统一/自定义元素的遍历，设计迭代器接口来实现

## 问题

1. 是否考虑批量入队/出队操作？
2. 是否考虑队列元素的转移清空操作？
