### ISSUE TITLE
queue: 线程安全的优先级队列

### ISSUE THREAD

**Issue by flycash** [gotomicro/ekit#105]
**仅限中文**

### 使用场景

在一些业务里面，我们会不断地往队列里面增加元素，但是在取出元素的时候，我们希望是按照优先级来取的。

同时在没有元素的时候，我们希望能够阻塞住，并且能够控制阻塞的时间。

优先级队列是否应该无界，需要进一步讨论。

### 行业分析
> 如果你知道有框架提供了类似功能，可以在这里描述，并且给出文档或者例子

### 可行方案
> 如果你有设计思路或者解决方案，请在这里提供。你可以提供多个方案，并且给出自己的选择

优先级队列，基本思路应该是使用大顶堆或者小顶堆。这里我们可以认为优先级是按照从高到低排序，即我们永远优先取出来优先级最高的队列。

### 其它

你需要：
- 给出设计文档
- 提供实现
- 提供基准测试

### 你设置的的 Go 环境?
> 上传 `go env` 的结果

**Comment by flyhigher139** [comment]
优先级队列的接口，和普通队列是一样的，仅入队出队的实现逻辑不同，故如下设计，另优先级队列的实现，可以考虑提供`PriorityArrayQueue`和`PriorityLinkedQueue`两种形式，分别用“切片”和“链表”作为元素的底层存储

```
type Queue[T any] interface {
	Offer(e T) (bool, error)
	Poll() T
	Peek() T
}

type PriorityQueue[T any] interface {
	Queue[T]
}
```
