### ISSUE TITLE
LinkedList: 修改capacity的业务逻辑

### ISSUE THREAD

**Issue by flyhigher139** [gotomicro/ekit#112]
**仅限中文**

在提之前请先查找[已有 issues](https://github.com/gotomicro/eorm/issues)，避免重复上报。

并且确保自己已经：
- [x] 阅读过文档
- [x] 阅读过注释
- [x] 阅读过例子

### 问题简要描述

1. 基于 #110 对capacity的讨论，当前LinkedList的Cap() 返回链表当前长度不是很合理，与PriotityQueue中对capacity和length的定义不完全一致
2. 现在LinkedList是无界的，可以增强为通过用户输入创建有界或无界的LinkedList
3. 虽然可以通过组合新增有界LinkedList，但由于队列的设计要依托于链表，队列本身是分有界和无界的，如果分别基于不同的链表实现两种队列，也与已实现的PriorityQueue行为不一致

故不如从根上解决，统一LinkedList和PriorityQueue关于 capacity的业务逻辑，并把LinkedList增强为同时支持有界和无界

### 修改思路

1. LinkedList增加capacity属性，`capacity <= 0`表示无界，否则为有界
2.  LinkedList已有的length属性，表示链表的当前长度，业务逻辑要与capacity有所区分
3. `Append()`和`Add()`方法，增加对于`capacity`的边界检查
4. 增加`CapacityOption`，创建LinkedList时，通过该参数控制新建的链表为有界或无界

### 你设置的的 Go 环境?
> 上传 `go env` 的结果

**Comment by flycash** [comment]
如我在合并请求评论的，LinkedList 本身保持无界是没有什么问题的。要是利用 LinkedList 来实现什么有界的，应该也是二次封装来达成目标

**Comment by flyhigher139** [comment]
好的～
