### ISSUE TITLE
list: Append 方法改造为不定参数形式

### ISSUE THREAD

**Issue by flycash** [gotomicro/ekit#36]
**仅限中文**

### 使用场景

在设计 List 接口的时候，我将 Append 设计为只接收一个参数，但是在实际中我们很可能会遇到 Append 多个元素的场景。

在这种考虑之下，我们应该将 List 的 Append 方法改造为不定参数：
```go
Append(ts...T) error
```

### 行业分析
> 如果你知道有框架提供了类似功能，可以在这里描述，并且给出文档或者例子

Go 本身的切片操作， append 就是允许追加多个的，例如：
```go
s := []int{1, 2, 3}
s = append(s, 4, 5, 6)
```

### 可行方案
> 如果你有设计思路或者解决方案，请在这里提供。你可以提供多个方案，并且给出自己的选择

注意到，我前面的不定参数方案并没有返回实际追加了多少个。一种可能的方案是：
```go
Append(ts...T)(cnt int, err error)
```
即在 Append 之后返回真实追加的元素个数。不过我觉得没有必要这么设计，道理很简单：在部分成功的情况下，用户不应该再使用这个 List 了，它已经处于一种不稳定状态。

如果用户真的有这种需求，他可以自己用装饰器模式重新封装 List，然后自己计数。

### 其它
> 任何你觉得有利于解决问题的补充说明

### 你设置的的 Go 环境?
> 上传 `go env` 的结果

**Comment by flycash** [comment]
注意：在修改了接口定义之后，你还需要修改相应的实现

**Comment by mousseqin** [comment]
老师我来试着改改看
