### ISSUE TITLE
sqlx: 加密列支持

### ISSUE THREAD

**Issue by flycash** [gotomicro/ekit#53]
**仅限中文**

### 使用场景

有一些时候我们处于安全的考虑，会考虑将存储在数据库中的数据进行加密。但是这种加密后的数据还需要解密出来才能使用。比如说在用户的个人信息里面，当我们存储用户的身份证号码的时候，就需要进行加密。但是我们在前端展示的时候，又需要解密之后展示出来。

在这种情况下，我们就需要对列进行加密和解密。

一般情况下，这种需求可以直接通过数据库的加密功能来完成。但是很多时候数据库性能都是瓶颈，所以我们不希望数据库承担这种加密和解密的职责。

所以我们可以选择在应用层面上对列进行加密和解密。

加密和解密的过程是一个和具体业务没有太多关系的东西，或者说加密和解密的过程不应该侵入到业务逻辑中。所以在这种情况下，我们可以考虑提供一个扩展的加密列的实现。

### 行业分析
> 如果你知道有框架提供了类似功能，可以在这里描述，并且给出文档或者例子

在我们的 sqlx 包里面，已经利用了类似的技术，[实现了 JSON 列](https://github.com/gotomicro/ekit/blob/dev/sqlx/json.go)：
```go
type JsonColumn[T any] struct {
	Val   T
	Valid bool
}
```

### 可行方案
> 如果你有设计思路或者解决方案，请在这里提供。你可以提供多个方案，并且给出自己的选择

我已经定义好了接口：https://github.com/gotomicro/ekit/blob/dev/sqlx/encrypt.go

我们可以通过实现 driver.Valuer 和 sql.Scanner 两个接口来无侵入地提供这种功能：
```go
// EncryptColumn 代表一个加密的列
// 一般来说加密可以选择依赖于数据库进行加密
// EncryptColumn 并不打算使用极其难破解的加密算法
// 而是选择使用 AES GCM 模式。
// 如果你觉得安全性不够，那么你可以考虑自己实现类似的结构体.
type EncryptColumn[T any] struct {
	Val T
	// Valid 为 true 的时候，Val 才有意义
	Valid bool
}

// Value 返回加密后的值
// 如果 T 是基本类型，那么会对 T 进行直接加密
// 否则，将 T 按照 JSON 序列化之后进行加密，返回加密后的数据
func (e EncryptColumn[T]) Value() (driver.Value, error) {
	//TODO implement me
	panic("implement me")
}

// Scan 方法会把写入的数据转化进行解密，
// 并将解密后的数据进行反序列化，构造 T
func (e *EncryptColumn[T]) Scan(src any) error {
	//TODO implement me
	panic("implement me")
}
```

### 其它
> 任何你觉得有利于解决问题的补充说明

正如类型定义里面提到的，这种加密并不是非常强调安全性，而是给一些有点敏感但是又不是特别敏感的数据提供的一种通用的加密支持。如果用户需要更加安全的加密手段，那么他们可以考虑参考这个实现设计一个类似的结构体。

所以我们这里只需要选择一个通用性强的，安全性也不错的算法，在这里我选择了额 AES 的 GCM 模式。从性能上来说它很不错，从破解难度上来说，也还不错。

如果你有更好的加密算法，也可以提出来。从安全性和性能两方面阐述选择它的理由。

实现这个结构体之后，你需要：
- 设计测试用例：需要考虑用户使用基本类型，内置类型，结构体等各种情况
- benchmark 测试：测试加密的性能，以 string 作为加密对象

### 你设置的的 Go 环境?
> 上传 `go env` 的结果

**Comment by longyue0521** [comment]
```go
type EncryptColumn[T any] struct {
	Val T
	// Valid 为 true 的时候，Val 才有意义
	Valid bool
}
```

### T的类型范围问题

- 数值 int/uint int8/uint8 int16/uint16 int32/uint32 int64/uint64 float32 float64 complex64 complex
- 布尔 bool
- 字节 byte
- 时间 time.Time
- 字符串 string
- 结构体类型

1. T是否可以为以上全部类型的指针/?还是部分?
2. T是否可以为以上全部类型的切片?还是部分?
3. T是否可以为以上全部类型的数组? 还是部分?
4. T是否可以为map?
5. 结构体类型中是否包括sql.NullXXX——sql.NullBool

### Value()方法的接受者及返回值问题

```go
func (e EncryptColumn[T]) Value() (driver.Value, error) {

}
```
6. Value方法的接受者设置为EncryptColumn[T]而不是*EncryptColumn[T]的原因?
7. driver.Value本质是any,可否规定为[]byte

### Scan(src any)中src的具体类型

8. 如果driver.Value限定为[]byte那么Scan中src也会被限制为[]byte即src类型范围与driver.Value的真实类型范围相匹配

**Comment by ccchooko** [comment]
@flycash @longyue0521 

这里面有个疑问想一起请教下，这里实现的时候，不管是对EncryptColumn还是JsonColumn都有同样的疑问。就是对定义的结构体的值如何传递的？下面是问题的具体说明

假如我定义的结构体长这样
```go
type EncryptColumn[T any] struct {
	Val T  // 实际值
	Valid bool  // 表示数据是否读到
	Key   []byte  // 加密用到的key
}
```

db实际写入和读取的流程应该是下面这个测试代码这样，问题就在第2点，读取的时候如何获取key并用key解密？(假设我知道key就能对加密数据解密)

```go
func Test_EncryptColumn(t *testing.T) {
	db, err := sql.Open("sqlite3", "./test.db")
        // ...

	_, err = db.ExecContext(ctx, `
CREATE TABLE IF NOT EXISTS my_json_model(
    id INTEGER PRIMARY KEY,
    address TEXT NOT NULL
)
`)
        
        // 1. 执行插入，调用Value()方法，这里在结构中设置了 加密的Key，和表示字段是否存在的Valid值
	res, _ := db.ExecContext(ctx, "INSERT INTO `my_json_model`(`id`, `address`)"+
		"VALUES (?, ?)", 1,
		EncryptColumn[Address]{
			Val: Address{
				City:     "xinyang",
				Province: "henan",
			},
			Key:   []byte("the-key-has-to-be-32-bytes-long!"),
			Valid: true,
		})

        // 2. 这里进行数据的读取，执行Scan方法进行解密操作，那么在第1步中设置的 Key 和 Valid如何传入到Scan()中呢？
	row := db.QueryRowContext(ctx, "SELECT `id`, `address` FROM `my_json_model` LIMIT 1")
	
       // 3. 读取
        var u User1
	_ = row.Scan(&u.Id, &u.Address)


       // ...
}

```


最后，如果key作为一个全局变量，而不是放入EncryptColumn结构体中，会有啥问题吗？

**Comment by longyue0521** [comment]
1. 在Value()返回时,将key的len和内容拼接在前面真实value前面 -> []byte{len(key), key, real_value}, 当你scan的时候,先拿到len(key),len(key)字节数固定.再根据len(key)内容分割key和real_value.这种做法类似于TCP自定义协议,将协议头长度放在前面,因为是固定的几个字节.

2. Key作为全局变量,可能有data race(误用,并发读写),数据安全问题.一个key被猜到,是只有一个列受影响,还是所有列受影响的问题.

**Comment by ccchooko** [comment]
> 1. 在Value()返回时,将key的len和内容拼接在前面真实value前面 -> []byte{len(key), key, real_value}, 当你scan的时候,先拿到len(key),len(key)字节数固定.再根据len(key)内容分割key和real_value.这种做法类似于TCP自定义协议,将协议头长度放在前面,因为是固定的几个字节.
> 2. Key作为全局变量,可能有data race(误用,并发读写),数据安全问题.一个key被猜到,是只有一个列受影响,还是所有列受影响的问题.

非常感谢回复。就是对于1这里有个疑问，**[]byte{len(key), key, real_value}** 这块：
1. 如果real_value是加密后的值，这么拼接放到数据库，Scan的时候相当于是直接把key暴露出来了，所有人就能根据这个key直接解密；
2. 如果real_value是原值，那么还是没有办法传递key的

**Comment by longyue0521** [comment]
real_value是加密后的值或许叫encrypted_value更合适,Scan看到是字节切片是无结构的 , Scan方法实现者才能“看到”[]byte内部结构,并解析出value. 

如果想要解密
首先,他得知道[]byte的内部结构是{len(key), key, encrypted_value} 而不是{encrypted_value,key,len(key)}等等其他结构
其次,他得知道len(key)是多少?才能从上面的结构中找到key
再次,他得知道用的什么加密算法才能用key和encrypted_value得到value

你可以具体说说 “所有人“指的是谁

**Comment by ccchooko** [comment]
> real_value是加密后的值或许叫encrypted_value更合适,Scan看到是字节切片是无结构的 , Scan方法实现者才能“看到”[]byte内部结构,并解析出value.
> 
> 如果想要解密 首先,他得知道[]byte的内部结构是{len(key), key, encrypted_value} 而不是{encrypted_value,key,len(key)}等等其他结构 其次,他得知道len(key)是多少?才能从上面的结构中找到key 再次,他得知道用的什么加密算法才能用key和encrypted_value得到value
> 
> 你可以具体说说 “所有人“指的是谁

这些是不是可以通过看源码获取到，因为工具的话还是面向开发者的

**Comment by longyue0521** [comment]
> 这些是不是可以通过看源码获取到，因为工具的话还是面向开发者的

同组的同事必然会知道,因为可以无限制翻看源码和数据库.你可以具体描述一下这种做法你的担心点再哪里?

**Comment by ccchooko** [comment]
> > 这些是不是可以通过看源码获取到，因为工具的话还是面向开发者的
> 
> 同组的同事必然会知道,因为可以无限制翻看源码和数据库.你可以具体描述一下这种做法你的担心点再哪里?

个人看法哈，如果需求是加密，数据即使开放了源码，也不能够解密。

假如像{len(key), key, encrypted_value} 这种方式加密，一旦知道规则之后就能解密了。如果代码不开源仅是公司内部使用我觉得没啥问题，但是如果代码是开源，开发者知道了这种规则就能拿到key解密了。
感觉这样还不如直接base64，相当于就是密码这种敏感数据不明文展示了，这种情况也没必要aes-gcm这种加密了。

就是核心需求是看，是为了不明文展示，还是说为了加密。如果是前者我觉得base64这种就能符合需求，如果是后者我觉得{len(key), key, encrypted_value}不是一个完美的方案

**Comment by longyue0521** [comment]
看了你的base64方案,我觉得我们的讨论偏离了需求, 让我们先回到需求

>使用场景
有一些时候我们处于安全的考虑，会考虑将存储在数据库中的数据进行加密。但是这种加密后的数据还需要解密出来才能使用。比如说在用户的个人信息里面，当我们存储用户的身份证号码的时候，就需要进行加密。但是我们在前端展示的时候，又需要解密之后展示出来。

>在这种情况下，我们就需要对列进行加密和解密。

>一般情况下，这种需求可以直接通过数据库的加密功能来完成。但是很多时候数据库性能都是瓶颈，所以我们不希望数据库承担这种加密和解密的职责。

>所以我们可以选择在应用层面上对列进行加密和解密。

>加密和解密的过程是一个和具体业务没有太多关系的东西，或者说加密和解密的过程不应该侵入到业务逻辑中。所以在这种情况下，我们可以考虑提供一个扩展的加密列的实现。


`个人看法哈，如果需求是加密，数据即使开放了源码，也不能够解密` 开放源码也不能解密,意味着源码不能包含加/解密的细节.因为看到加密的细节也可以知道上面那个[]byte结构,或者反推解密的步骤啊.

如果真的要做到这种程度,那就需要用到数据库层面的加密,而上面的需求也说明了不这么做的原因`很多时候数据库性能都是瓶颈，所以我们不希望数据库承担这种加密和解密的职责。`

我认为,没有完美的解决方案,只有在约束条件下适合的解决方案. 

这里的约束是数据库层面加解密不能用影响性能,但还要求对数据进行加密存储,解密展示. 那这部分功能放哪实现呢? 

我只能写源码里, 要不你说说你的方案

源码和数据都是公司的重要的资产,被外界拿到会算作事故,负责安全的同事要背锅的. 即使开放源码也会第一时间被要求脱敏并再三审查的

**Comment by flycash** [comment]
实际上，这个问题讨论有点偏离我们工具库的设计了。

我们在实现里面维护一个 key，比如说在 EncryptedColumn 里面维护一个 key 是可以的。这个 key 运行的时候放在内存里，如果用户知道内存地址，肯定可以获得。但是正常来说，我们不考虑这种问题。

那么剩下的问题就是，key 保存在代码里面。但是这个本质上是用户使用的问题：
```go
c := &EncryptedColumn {
    key: "my key" ,
}
```
用户硬要这么写，那是他自己承担风险。

而如果用户不那么写，他可以尝试从远程配置中心读取：
```go
key := readFromEtcd()
c := &EncryptedColumn{}
```
那么密钥泄露的问题就交给了 etcd 了。

如果用户自己采用复杂的策略来生成这个 key，例如
```go
key := computeByUserID(uid)
```
那么 key 泄露也是用户的问题，因为他的同事可以看到代码。

只是这种我们都交给用户去决策。作为一个单一的工具类，我们不管他怎么管 key。

又比如，设计 crypto 库的人，也不会管我们怎么搞 key，但是它要求有一个 key
