### ISSUE TITLE
list: ArrayList Delete 方法缩容

### ISSUE THREAD

**Issue by flycash** [gotomicro/ekit#59]
**仅限中文**

### 使用场景

在一些特殊的场景下，我们可能创建了一个巨大的切片，而后不断删除不断删除之后，可能只剩下很少的一部分元素。在这种情况下，我们现在的 ArrayList 的实现，依赖于切片，所以最终底层那个庞大的数组始终存活着，会浪费一部分内存。

因此我们可以考虑，在 Delete 方法里面支持缩容。

### 可行方案

缩容的核心问题是，什么时候应该缩容？缩到什么地步？
当已有元素远远少于容量的时候，就应该缩容。缩容的策略是依据切片的扩容策略来决定。例如说目前切片的扩容策略 < 1024 则直接两倍，1024 之后则是 1.25 扩容。

那么相应的缩容就是：
1. 如果当前容量 <=2048，那么就在已有元素是容量的四分之一的时候，就执行缩容，缩到原本的一半（要防止将来扩容）
2. 如果当前容量 > 2048，那么在已有元素是容量的 1/2 的时候就可以缩容，缩到已有容量的 5/8

选择 2048 作为阈值，是因为 2048/2 = 1024 恰好是原本扩容的分界点。那么 2048 的 5/8 相比已有的元素数量，还有两百多个位置，后续即便不断增加元素，引起扩容的概率也小很多。

缩容还有另外一个问题。当容量小于一个固定阈值的时候，不需要继续缩容了。这个阈值，我认为 16,32, 64 都可以接受。因为即便不缩容，浪费的空间也不会很多。

此外，这两个阈值要对用户完全透明，即用户不允许控制这两个参数，后续我们可以进一步调研行业标准，来调整这些阈值。

### 其它
> 任何你觉得有利于解决问题的补充说明

如果你对缩容策略有什么想法，也可以在下面补充

### 你设置的的 Go 环境?
> 上传 `go env` 的结果

**Comment by mousseqin** [comment]
我的第一想法是：如果某个切片满足某个阈值，重新申请一个切片->设定新的cap（是原切片的 5/8）-> 把值迁移过去 -> 最后把原切片注销？

**Comment by flycash** [comment]
不需要注销，垃圾回收就会回收掉它
