### ISSUE TITLE
slice： 切片辅助方法

### ISSUE THREAD

**Issue by flycash** [gotomicro/ekit#69]
**仅限中文**

### 使用场景
切片应该是日常中使用最多的一种数据结构了。
但是切片本身的操作非常有限，所以很多时候我们需要一些辅助方法。在有了泛型的支持下，这些辅助方法将会变得对用户非常友好。
目前我已经定义了一些辅助方法，在 https://github.com/gotomicro/ekit/tree/dev/slice

切片的这些辅助方法分成：
- 索引类： index 文件内的方法
- 映射类：map 文件里面的方法
- 查找类：contains 文件里面的方法
- 交集：intersect 文件里面的方法
- 并集：union 文件里面的方法
- 差集：diff 文件里面的方法

### 行业分析
> 如果你知道有框架提供了类似功能，可以在这里描述，并且给出文档或者例子

### 可行方案
> 如果你有设计思路或者解决方案，请在这里提供。你可以提供多个方案，并且给出自己的选择

### 其它
> 任何你觉得有利于解决问题的补充说明

- 你可以选择其中的一类来实现，不要一次性写完，太多了我看不过来，一类一类来
- 你需要设计测试用例，尤其是考虑 nil，空切片等情况
- 你需要写例子，查看 [Go 例子写法](https://go.dev/blog/examples)
- 你可以提供更加多的方法，但是依旧要提供注释，测试用例和例子

### 你设置的的 Go 环境?
> 上传 `go env` 的结果

**Comment by flyhigher139** [comment]
有没有必要设计一个Set接口，让Set来支持这些操作，Set的实现，可以用slice，也可以用map？

**Comment by aristletl** [comment]
现在对需求有些疑问：
这些对切片的操作最后的到的结果中是否允许重复元素存在呢？
比如[1, 2, 2, 3, 3, 4, 5]与[2, 2, 6]
diff的结果是[1, 3, 3, 4, 5]还是[1, 3, 4, 5]呢？
intersect的结果是[2, 2]还是[2]?
union的结果是[1, 2, 2, 3, 3, 4, 5, 6]还是[1, 2, 3, 4, 5, 6]?

**Comment by longyue0521** [comment]
@aristletl  严格数学意义上的并集、交集、差集及对称差集,所以需要去重

**Comment by flyhigher139** [comment]
> @aristletl 严格数学意义上的并集、交集、差集及对称差集,所以需要去重

@longyue0521 所以是不是应该先定义个Set接口，或Set的数据结构，在此基础上再去做并集、交集和差集，我觉得集合操作在代码里处理数据时还挺有用的

**Comment by flyhigher139** [comment]
看到Diff，我第一反应是取两个集合的差集。所以，我是把Diff视为集合运算的，而集合，是要求元素不重合的。

切片允许元素重合，做diff，我个人感觉有点奇怪，如果要实现，就避免和集合混淆，不做去重了吧

**Comment by flycash** [comment]
其实不是说这个操作是集合的专属操作，在 .Net 和 java 里面都有对 List 类结构求差集。所以本身这种还是会被广泛使用的。我觉得如果你的第一直觉也是要去重，那么我们保持去重的语义。如果后续需要非去重的语义，那么我们就可以考虑提供新的方法

**Comment by flycash** [comment]
那么我觉得，可以每个方法加个 Set 后缀，这样会更加清晰一点

**Comment by longyue0521** [comment]
1. 看到Diff会联想到差集,进而联想到数学中集合的概念,不去重.
2. 如果不想换名字,可以在注释中说明一下不去重.但我还是建议如果不做去重,就换个名字,哪怕丑点也行.
4. 用Diff但不去重,使得Diff和Union等其他集合操作逻辑语义不统一

**Comment by longyue0521** [comment]
增加一个包名, set.Diff, set.Union

**Comment by flycash** [comment]
但是 set.Diff 接收切片作为参数，就很奇怪

**Comment by flycash** [comment]
我们确实是会设计一个 set 包，里面就是正儿八经的 Set 数据结构

**Comment by longyue0521** [comment]
slice.Union 不去重
slice.UnionAsSet 去重

**Comment by flycash** [comment]
我感觉没必要使用 As，Diff 不去重，DiffSet 去重。Union 不去重，UnionSet 去重，然后 IntersectionSet 去重，Intersection 不去重，这样？

**Comment by longyue0521** [comment]
我觉得加As更符合英文语法,不加也可以

**Comment by flyhigher139** [comment]
如果要符合英文的话，命名为AsSet ，返回值也得改为Set

**Comment by flycash** [comment]
看做短语，就不需要 SET，就不加了。这个不用特别在意，
